### ISSUE TITLE
Fix Intellij highlight errors

### ISSUE THREAD

**Issue by xeno-by** [twitter/reasonable-scala#13]
At the moment, IntelliJ doesn't work well on the Rsc codebase. After opening our project in IntelliJ, you may experience incomplete code intelligence, spurious red squiggles and other unpleasant issues. We believe that this is the case because of insufficient support for sbt-crossproject that we use to crosscompile Rsc to both JVM and Native. We haven't yet found a good workaround for this problem.

**Comment by niktrop** [comment]
@xeno-by It seems that most of the problems are caused by a conflict between a standard scala-library and scalalib_native. Class files in scalalib_native0.3_2.11-0.3.3.jar do not contain scalasig annotation and can't be decompiled normally. As a temporary workaround you may just remove scalalib-native from the list of the libraries after importing project.

**Comment by rorygraves** [comment]
I was going to mention the same thing, This fix works well for me.

**Comment by xeno-by** [comment]
Workaround documented in https://github.com/twitter/reasonable-scala/pull/27. I'll be closing this issue.
